In [1]:
import pandas as pd
import numpy as np
import json

In [2]:
# load the collected datapoints json file
df_yoga = pd.read_json('model/datapoints-ml5/yoga.json')

In [3]:
df_yoga_val = pd.read_json('model/datapoints-ml5/soumya-training.json')

In [45]:
# with pd.option_context('display.max_rows',None,'display.max_columns',None):
print(df_yoga)

                                                   data
0     {'xs': {'0': 265.4053324963826, '1': 263.00019...
1     {'xs': {'0': 265.4053324963826, '1': 263.00019...
2     {'xs': {'0': 273.27526685552493, '1': 263.4545...
3     {'xs': {'0': 273.27526685552493, '1': 263.4545...
4     {'xs': {'0': 273.27526685552493, '1': 263.4545...
...                                                 ...
3664  {'xs': {'0': 354.3905301063502, '1': 334.18770...
3665  {'xs': {'0': 353.53565536145953, '1': 330.8824...
3666  {'xs': {'0': 351.02515053476293, '1': 333.6118...
3667  {'xs': {'0': 346.42412131427824, '1': 333.4233...
3668  {'xs': {'0': 352.81592789454635, '1': 336.4396...

[3669 rows x 1 columns]

In [5]:
# to get the individual angles of a pose
# for i in range(14):
#     print(df_yoga.at[0,'data'].get('xs').get(str(i)))

In [6]:
# to get the label
# df_yoga.at[0,'data'].get('ys').get('0')

In [7]:
columns = ['a0', 'a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7', 'a8', 'a9', 'a10', 'a11', 'a12', 'a13', 'pose']
df_filtered = pd.DataFrame(columns=columns)

In [8]:
df_filtered_test = pd.DataFrame(columns=columns)

In [9]:
# len(df_yoga.at[0,'data'].get('xs'))

In [14]:
# putting everything together for the training data
# loop through the pandas yoga rows
for i in range(len(df_yoga)):
    temp_arr = []
    # get the points first
    for j in range(14):
        temp_arr.append(df_yoga.at[i,'data'].get('xs').get(str(j)))
    # get the label
    temp_arr.append(df_yoga.at[i,'data'].get('ys').get('0'))
    df_filtered.loc[i] = temp_arr
df_filtered

,a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,pose
0,265.405332,263.000193,279.886341,257.806562,68.595548,114.238489,268.819495,268.251005,72.267832,105.411831,71.835177,108.033624,68.101067,113.559199,Mountain
1,265.405332,263.000193,279.886341,257.806562,68.595548,114.238489,268.819495,268.251005,72.267832,105.411831,71.835177,108.033624,68.101067,113.559199,Mountain
2,273.275267,263.454578,275.091656,257.369954,69.419626,114.136569,269.984494,269.552032,73.139609,105.616622,71.328416,108.308774,69.413078,113.949740,Mountain
3,273.275267,263.454578,275.091656,257.369954,69.419626,114.136569,269.984494,269.552032,73.139609,105.616622,71.328416,108.308774,69.413078,113.949740,Mountain
4,273.275267,263.454578,275.091656,257.369954,69.419626,114.136569,269.984494,269.552032,73.139609,105.616622,71.328416,108.308774,69.413078,113.949740,Mountain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3664,354.390530,334.187700,270.013641,229.634137,25.692325,73.407152,265.167445,304.544013,29.191564,82.425752,23.053465,71.374544,23.047126,84.157665,Warrior 2
3665,353.535655,330.882497,271.113020,213.900575,24.639241,179.259830,267.188407,287.896739,29.170251,176.315453,23.623870,168.121853,23.106678,187.793086,Warrior 2
3666,351.025151,333.611834,267.406741,231.325003,25.488751,35.818644,268.151565,238.641573,29.230613,9.943084,23.286777,358.659584,24.465269,10.757319,Warrior 2
3667,346.424121,333.423326,269.028146,214.706653,18.957976,177.416679,278.045146,287.721457,28.028451,175.781801,22.849084,166.603327,23.292347,186.595684,Warrior 2
3668,352.815928,336.439676,270.895469,229.265524,23.542116,357.684727,268.690614,284.876098,29.030261,3.525416,23.235704,351.755861,22.822919,4.820238,Warrior 2

In [41]:
# find the average of each angle for mountain
df_mountain = df_filtered.loc[df_filtered['pose'] == 'Mountain']
a0 = 0
a1 = 0
a2 = 0
a3 = 0
a4 = 0
a5 = 0
a6 = 0
a7 = 0
a8 = 0
a9 = 0
a10 = 0
a11 = 0
a12 = 0
a13 = 0

# loop through each angle
# a0
for i in df_mountain['a0']:
    a0 += i
a0_ave = a0 / len(df_mountain)

print(f'average of a0: {a0_ave}')

# a1
for i in df_mountain['a1']:
    a1 += i
a1_ave = a1 / len(df_mountain)

print(f'average of a1: {a1_ave}')

# a2
for i in df_mountain['a2']:
    a2 += i
a2_ave = a2 / len(df_mountain)

print(f'average of a2: {a2_ave}')

# a3
for i in df_mountain['a3']:
    a3 += i
a3_ave = a3 / len(df_mountain)

print(f'average of a3: {a3_ave}')

# a4
for i in df_mountain['a4']:
    a4 += i
a4_ave = a4 / len(df_mountain)

print(f'average of a4: {a4_ave}')

# a5
for i in df_mountain['a5']:
    a5 += i
a5_ave = a5 / len(df_mountain)

print(f'average of a5: {a5_ave}')

# a0
for i in df_mountain['a6']:
    a6 += i
a6_ave = a6 / len(df_mountain)

print(f'average of a6: {a6_ave}')

# a7
for i in df_mountain['a7']:
    a7 += i
a7_ave = a7 / len(df_mountain)

print(f'average of a7: {a7_ave}')

# a8
for i in df_mountain['a8']:
    a8 += i
a8_ave = a8 / len(df_mountain)

print(f'average of a8: {a8_ave}')

# a9
for i in df_mountain['a9']:
    a9 += i
a9_ave = a9 / len(df_mountain)

print(f'average of a9: {a9_ave}')

# a10
for i in df_mountain['a10']:
    a10 += i
a10_ave = a10 / len(df_mountain)

print(f'average of a10: {a10_ave}')

# a11
for i in df_mountain['a11']:
    a11 += i
a11_ave = a11 / len(df_mountain)

print(f'average of a11: {a11_ave}')

# a12
for i in df_mountain['a12']:
    a12 += i
a12_ave = a12 / len(df_mountain)

print(f'average of a12: {a12_ave}')

# a13
for i in df_mountain['a13']:
    a13 += i
a13_ave = a13 / len(df_mountain)

print(f'average of a13: {a13_ave}')

average of a0: 267.92894477076163
average of a1: 267.8780003541165
average of a2: 277.3238868249885
average of a3: 259.9553736248052
average of a4: 67.79409019955855
average of a5: 113.05005891225755
average of a6: 271.2225081996758
average of a7: 274.2705337344385
average of a8: 71.86728094123826
average of a9: 108.55981758065309
average of a10: 71.23896710298241
average of a11: 110.48009368058477
average of a12: 68.2499478038741
average of a13: 114.95071948883633

In [ ]:
# find the average of each angle for tree
df_tree = df_filtered.loc[df_filtered['pose'] == 'Tree']
a0 = 0
a1 = 0
a2 = 0
a3 = 0
a4 = 0
a5 = 0
a6 = 0
a7 = 0
a8 = 0
a9 = 0
a10 = 0
a11 = 0
a12 = 0
a13 = 0

# loop through each angle
# a0
for i in df_tree['a0']:
    a0 += i
a0_ave = a0 / len(df_tree)

print(f'average of a0: {a0_ave}')

# a1
for i in df_tree['a1']:
    a1 += i
a1_ave = a1 / len(df_tree)

print(f'average of a1: {a1_ave}')

# a2
for i in df_tree['a2']:
    a2 += i
a2_ave = a2 / len(df_tree)

print(f'average of a2: {a2_ave}')

# a3
for i in df_tree['a3']:
    a3 += i
a3_ave = a3 / len(df_tree)

print(f'average of a3: {a3_ave}')

# a4
for i in df_tree['a4']:
    a4 += i
a4_ave = a4 / len(df_tree)

print(f'average of a4: {a4_ave}')

# a5
for i in df_tree['a5']:
    a5 += i
a5_ave = a5 / len(df_tree)

print(f'average of a5: {a5_ave}')

# a0
for i in df_tree['a6']:
    a6 += i
a6_ave = a6 / len(df_tree)

print(f'average of a6: {a6_ave}')

# a7
for i in df_tree['a7']:
    a7 += i
a7_ave = a7 / len(df_tree)

print(f'average of a7: {a7_ave}')

# a8
for i in df_tree['a8']:
    a8 += i
a8_ave = a8 / len(df_tree)

print(f'average of a8: {a8_ave}')

# a9
for i in df_tree['a9']:
    a9 += i
a9_ave = a9 / len(df_tree)

print(f'average of a9: {a9_ave}')

# a10
for i in df_tree['a10']:
    a10 += i
a10_ave = a10 / len(df_tree)

print(f'average of a10: {a10_ave}')

# a11
for i in df_tree['a11']:
    a11 += i
a11_ave = a11 / len(df_tree)

print(f'average of a11: {a11_ave}')

# a12
for i in df_tree['a12']:
    a12 += i
a12_ave = a12 / len(df_tree)

print(f'average of a12: {a12_ave}')

# a13
for i in df_tree['a13']:
    a13 += i
a13_ave = a13 / len(df_tree)

print(f'average of a13: {a13_ave}')

In [44]:
# find the average of each angle for goddess
df_goddess = df_filtered.loc[df_filtered['pose'] == 'Goddess']
a0 = 0
a1 = 0
a2 = 0
a3 = 0
a4 = 0
a5 = 0
a6 = 0
a7 = 0
a8 = 0
a9 = 0
a10 = 0
a11 = 0
a12 = 0
a13 = 0

# loop through each angle
# a0
for i in df_goddess['a0']:
    a0 += i
a0_ave = a0 / len(df_goddess)

print(f'average of a0: {a0_ave}')

# a1
for i in df_goddess['a1']:
    a1 += i
a1_ave = a1 / len(df_goddess)

print(f'average of a1: {a1_ave}')

# a2
for i in df_goddess['a2']:
    a2 += i
a2_ave = a2 / len(df_goddess)

print(f'average of a2: {a2_ave}')

# a3
for i in df_goddess['a3']:
    a3 += i
a3_ave = a3 / len(df_goddess)

print(f'average of a3: {a3_ave}')

# a4
for i in df_goddess['a4']:
    a4 += i
a4_ave = a4 / len(df_goddess)

print(f'average of a4: {a4_ave}')

# a5
for i in df_goddess['a5']:
    a5 += i
a5_ave = a5 / len(df_goddess)

print(f'average of a5: {a5_ave}')

# a0
for i in df_goddess['a6']:
    a6 += i
a6_ave = a6 / len(df_goddess)

print(f'average of a6: {a6_ave}')

# a7
for i in df_goddess['a7']:
    a7 += i
a7_ave = a7 / len(df_goddess)

print(f'average of a7: {a7_ave}')

# a8
for i in df_goddess['a8']:
    a8 += i
a8_ave = a8 / len(df_goddess)

print(f'average of a8: {a8_ave}')

# a9
for i in df_goddess['a9']:
    a9 += i
a9_ave = a9 / len(df_goddess)

print(f'average of a9: {a9_ave}')

# a10
for i in df_goddess['a10']:
    a10 += i
a10_ave = a10 / len(df_goddess)

print(f'average of a10: {a10_ave}')

# a11
for i in df_goddess['a11']:
    a11 += i
a11_ave = a11 / len(df_goddess)

print(f'average of a11: {a11_ave}')

# a12
for i in df_goddess['a12']:
    a12 += i
a12_ave = a12 / len(df_goddess)

print(f'average of a12: {a12_ave}')

# a13
for i in df_goddess['a13']:
    a13 += i
a13_ave = a13 / len(df_goddess)

print(f'average of a13: {a13_ave}')

average of a0: 225.88885592550653
average of a1: 289.77050330017727
average of a2: 307.4745261477588
average of a3: 237.38432674502604
average of a4: 76.15758200509772
average of a5: 128.91455784145754
average of a6: 153.43257420061298
average of a7: 146.67738812015926
average of a8: 225.0465274947821
average of a9: 128.01321786535468
average of a10: 174.48409168395932
average of a11: 122.92636830868251
average of a12: 227.64397007714732
average of a13: 135.78139548534

In [42]:
# find the average of each angle for goddess
df_warrior2 = df_filtered.loc[df_filtered['pose'] == 'Warrior 2']
a0 = 0
a1 = 0
a2 = 0
a3 = 0
a4 = 0
a5 = 0
a6 = 0
a7 = 0
a8 = 0
a9 = 0
a10 = 0
a11 = 0
a12 = 0
a13 = 0

# loop through each angle
# a0
for i in df_warrior2['a0']:
    a0 += i
a0_ave = a0 / len(df_warrior2)

print(f'average of a0: {a0_ave}')

# a1
for i in df_warrior2['a1']:
    a1 += i
a1_ave = a1 / len(df_warrior2)

print(f'average of a1: {a1_ave}')

# a2
for i in df_warrior2['a2']:
    a2 += i
a2_ave = a2 / len(df_warrior2)

print(f'average of a2: {a2_ave}')

# a3
for i in df_warrior2['a3']:
    a3 += i
a3_ave = a3 / len(df_warrior2)

print(f'average of a3: {a3_ave}')

# a4
for i in df_warrior2['a4']:
    a4 += i
a4_ave = a4 / len(df_warrior2)

print(f'average of a4: {a4_ave}')

# a5
for i in df_warrior2['a5']:
    a5 += i
a5_ave = a5 / len(df_warrior2)

print(f'average of a5: {a5_ave}')

# a0
for i in df_warrior2['a6']:
    a6 += i
a6_ave = a6 / len(df_warrior2)

print(f'average of a6: {a6_ave}')

# a7
for i in df_warrior2['a7']:
    a7 += i
a7_ave = a7 / len(df_warrior2)

print(f'average of a7: {a7_ave}')

# a8
for i in df_warrior2['a8']:
    a8 += i
a8_ave = a8 / len(df_warrior2)

print(f'average of a8: {a8_ave}')

# a9
for i in df_warrior2['a9']:
    a9 += i
a9_ave = a9 / len(df_warrior2)

print(f'average of a9: {a9_ave}')

# a10
for i in df_warrior2['a10']:
    a10 += i
a10_ave = a10 / len(df_warrior2)

print(f'average of a10: {a10_ave}')

# a11
for i in df_warrior2['a11']:
    a11 += i
a11_ave = a11 / len(df_warrior2)

print(f'average of a11: {a11_ave}')

# a12
for i in df_warrior2['a12']:
    a12 += i
a12_ave = a12 / len(df_warrior2)

print(f'average of a12: {a12_ave}')

# a13
for i in df_warrior2['a13']:
    a13 += i
a13_ave = a13 / len(df_warrior2)

print(f'average of a13: {a13_ave}')

average of a0: 254.2574417170418
average of a1: 297.9138227780071
average of a2: 296.2176716334106
average of a3: 242.57483782424563
average of a4: 76.04822758587075
average of a5: 130.35657220772438
average of a6: 257.86604953604416
average of a7: 232.2876329623176
average of a8: 40.0474076923995
average of a9: 134.587835937805
average of a10: 39.81237001227132
average of a11: 132.03137892303735
average of a12: 82.78598241066567
average of a13: 140.9961034041264

In [15]:
# putting everything together for the testing data
# loop through the pandas yoga rows
for i in range(len(df_yoga_val)):
    temp_arr = []
    # get the points first
    for j in range(14):
        temp_arr.append(df_yoga_val.at[i,'data'].get('xs').get(str(j)))
    # get the label
    temp_arr.append(df_yoga_val.at[i,'data'].get('ys').get('0'))
    df_filtered_test.loc[i] = temp_arr
df_filtered_test

,a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,pose
0,262.829400,272.297768,276.926342,257.941081,67.641550,122.928871,258.056956,269.202976,63.841200,115.259247,64.921927,116.320826,61.557433,122.541308,Mountain
1,266.112725,267.479192,280.590459,258.961041,68.864943,121.340929,252.881123,270.162924,65.552179,113.400655,65.042367,115.856119,60.014403,121.420859,Mountain
2,265.166085,268.103886,276.459497,258.426849,67.062957,121.761550,257.257441,269.082643,63.116732,113.103763,63.558144,115.587977,60.471362,121.314063,Mountain
3,286.304905,270.303705,262.840032,258.077288,74.220968,121.312036,255.046051,269.321693,66.789123,113.228404,63.667174,115.133414,66.759087,120.992829,Mountain
4,274.273069,274.021116,263.054334,258.831674,74.003741,121.103647,253.889758,269.585967,63.141926,114.853967,63.019975,115.418584,66.108154,120.908610,Mountain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1189,243.759122,294.891549,306.644064,239.816198,73.806410,131.688681,276.061574,267.204828,89.423282,120.933079,90.296500,119.107219,76.977954,130.495640,Warrior 2
1190,244.907487,285.394757,303.848545,234.404463,74.194208,132.855612,275.793908,268.791694,87.963464,116.744627,88.852482,118.723495,77.328716,132.356121,Warrior 2
1191,246.801035,279.330472,307.787391,241.595770,76.203089,132.871096,265.205311,265.284529,87.482738,117.349603,87.212316,119.574240,73.453599,130.790276,Warrior 2
1192,252.458518,274.431917,303.442322,245.160485,76.501370,129.967660,254.663172,266.329292,82.514443,115.791640,81.360307,119.088910,68.974721,128.404374,Warrior 2
1193,254.381720,269.202862,301.048837,250.580318,82.212792,129.007562,245.146984,269.575870,83.373278,117.672618,82.386351,121.172340,70.345865,128.823900,Warrior 2

In [12]:
# need to have numeric labels for tensorflow model
labels_num = []
pose_col = df_filtered['pose']
for i in range(len(pose_col)):
    if (pose_col[i]) == 'Mountain':
        labels_num.append(0)
    elif (pose_col[i]) == 'Tree':
        labels_num.append(1)
    elif (pose_col[i]) == 'Goddess':
        labels_num.append(2)
    elif (pose_col[i]) == 'Warrior 2':
        labels_num.append(3)
        
labels_num = np.array(labels_num)
# labels_num

In [13]:
# for testing data
labels_num_test = []
pose_col = df_filtered_test['pose']
for i in range(len(pose_col)):
    if (pose_col[i]) == 'Mountain':
        labels_num_test.append(0)
    elif (pose_col[i]) == 'Tree':
        labels_num_test.append(1)
    elif (pose_col[i]) == 'Goddess':
        labels_num_test.append(2)
    elif (pose_col[i]) == 'Warrior 2':
        labels_num_test.append(3)
        
labels_num_test = np.array(labels_num_test)
# labels_num_test

In [202]:
# dropping last col with pose names
df_filtered.drop(df_filtered.columns[-1], axis=1, inplace=True)

In [203]:
df_filtered_test.drop(df_filtered_test.columns[-1], axis=1, inplace=True)

In [204]:
# from sklearn.model_selection import train_test_split

In [205]:
# features_train, features_test, labels_train, labels_test = train_test_split(df_filtered, labels_num, test_size=0.30, random_state=42)

In [206]:
# scale the data
from sklearn.preprocessing import MinMaxScaler

In [207]:
scaler = MinMaxScaler()

In [208]:
# scale the training data
scaler.fit(df_filtered)

MinMaxScaler()

In [209]:
# scale the testing data
scaler.fit(df_filtered_test)

MinMaxScaler()

In [210]:
# norm the training data
features_train = scaler.transform(df_filtered)

In [211]:
# norm the validation data
features_test = scaler.transform(df_filtered_test)
# features_test = scaler.transform(features_test)

In [212]:
# features_train

In [213]:
# features_test

In [214]:
import tensorflow as tf

In [215]:
from tensorflow.keras.layers import Input, Dense, Activation, Dropout
from tensorflow.keras.models import Model

In [216]:
input_layer = Input(shape=(df_filtered.shape[1],))

In [217]:
dense_layer_1 = Dense(15, activation='relu')(input_layer)

In [218]:
dense_layer_2 = Dense(10, activation='relu')(dense_layer_1)

In [219]:
output = Dense(4, activation='softmax')(dense_layer_2)

In [220]:
model = Model(inputs=input_layer, outputs=output)

In [221]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['acc'])

In [222]:
history = model.fit(features_train,labels_num,batch_size=8,epochs=100,verbose=1)

Train on 2782 samples
Epoch 1/100
2782/2782 [==============================] - 0s 100us/sample - loss: 1.2606 - acc: 0.5712
Epoch 2/100
2782/2782 [==============================] - 0s 87us/sample - loss: 0.7485 - acc: 0.7189
Epoch 3/100
2782/2782 [==============================] - 0s 82us/sample - loss: 0.4194 - acc: 0.8659
Epoch 4/100
2782/2782 [==============================] - 0s 81us/sample - loss: 0.3195 - acc: 0.8961
Epoch 5/100
2782/2782 [==============================] - 0s 87us/sample - loss: 0.2763 - acc: 0.9058
Epoch 6/100
2782/2782 [==============================] - 0s 97us/sample - loss: 0.2506 - acc: 0.9148
Epoch 7/100
2782/2782 [==============================] - 0s 88us/sample - loss: 0.2322 - acc: 0.9198
Epoch 8/100
2782/2782 [==============================] - 0s 76us/sample - loss: 0.2152 - acc: 0.9263
Epoch 9/100
2782/2782 [==============================] - 0s 74us/sample - loss: 0.2031 - acc: 0.9310
Epoch 10/100
2782/2782 [==============================] - 0s 81us/sample - loss: 0.1926 - acc: 0.9317
Epoch 11/100
2782/2782 [==============================] - 0s 77us/sample - loss: 0.1827 - acc: 0.9382
Epoch 12/100
2782/2782 [==============================] - 0s 74us/sample - loss: 0.1736 - acc: 0.9418
Epoch 13/100
2782/2782 [==============================] - 0s 81us/sample - loss: 0.1643 - acc: 0.9450
Epoch 14/100
2782/2782 [==============================] - 0s 75us/sample - loss: 0.1573 - acc: 0.9493
Epoch 15/100
2782/2782 [==============================] - 0s 80us/sample - loss: 0.1533 - acc: 0.9493
Epoch 16/100
2782/2782 [==============================] - 0s 87us/sample - loss: 0.1449 - acc: 0.9526
Epoch 17/100
2782/2782 [==============================] - 0s 80us/sample - loss: 0.1408 - acc: 0.9526
Epoch 18/100
2782/2782 [==============================] - 0s 82us/sample - loss: 0.1351 - acc: 0.9533
Epoch 19/100
2782/2782 [==============================] - 0s 86us/sample - loss: 0.1313 - acc: 0.9590
Epoch 20/100
2782/2782 [==============================] - 0s 87us/sample - loss: 0.1259 - acc: 0.9576
Epoch 21/100
2782/2782 [==============================] - 0s 90us/sample - loss: 0.1211 - acc: 0.9594
Epoch 22/100
2782/2782 [==============================] - 0s 81us/sample - loss: 0.1142 - acc: 0.9615
Epoch 23/100
2782/2782 [==============================] - 0s 87us/sample - loss: 0.1131 - acc: 0.9630
Epoch 24/100
2782/2782 [==============================] - 0s 84us/sample - loss: 0.1105 - acc: 0.9615
Epoch 25/100
2782/2782 [==============================] - 0s 81us/sample - loss: 0.1038 - acc: 0.9662
Epoch 26/100
2782/2782 [==============================] - 0s 81us/sample - loss: 0.1009 - acc: 0.9709
Epoch 27/100
2782/2782 [==============================] - 0s 86us/sample - loss: 0.0989 - acc: 0.9694
Epoch 28/100
2782/2782 [==============================] - 0s 80us/sample - loss: 0.0961 - acc: 0.9680
Epoch 29/100
2782/2782 [==============================] - 0s 85us/sample - loss: 0.0911 - acc: 0.9691
Epoch 30/100
2782/2782 [==============================] - 0s 84us/sample - loss: 0.0924 - acc: 0.9716
Epoch 31/100
2782/2782 [==============================] - 0s 82us/sample - loss: 0.0888 - acc: 0.9716
Epoch 32/100
2782/2782 [==============================] - 0s 80us/sample - loss: 0.0836 - acc: 0.9745
Epoch 33/100
2782/2782 [==============================] - 0s 87us/sample - loss: 0.0838 - acc: 0.9727
Epoch 34/100
2782/2782 [==============================] - 0s 79us/sample - loss: 0.0805 - acc: 0.9741
Epoch 35/100
2782/2782 [==============================] - 0s 82us/sample - loss: 0.0794 - acc: 0.9752
Epoch 36/100
2782/2782 [==============================] - 0s 85us/sample - loss: 0.0763 - acc: 0.9752
Epoch 37/100
2782/2782 [==============================] - 0s 75us/sample - loss: 0.0775 - acc: 0.9723
Epoch 38/100
2782/2782 [==============================] - 0s 76us/sample - loss: 0.0773 - acc: 0.9752
Epoch 39/100
2782/2782 [==============================] - 0s 80us/sample - loss: 0.0727 - acc: 0.9777
Epoch 40/100
2782/2782 [==============================] - 0s 85us/sample - loss: 0.0742 - acc: 0.9777
Epoch 41/100
2782/2782 [==============================] - 0s 80us/sample - loss: 0.0702 - acc: 0.9759
Epoch 42/100
2782/2782 [==============================] - 0s 80us/sample - loss: 0.0696 - acc: 0.9756
Epoch 43/100
2782/2782 [==============================] - 0s 81us/sample - loss: 0.0692 - acc: 0.9795
Epoch 44/100
2782/2782 [==============================] - 0s 81us/sample - loss: 0.0695 - acc: 0.9770
Epoch 45/100
2782/2782 [==============================] - 0s 83us/sample - loss: 0.0708 - acc: 0.9752
Epoch 46/100
2782/2782 [==============================] - 0s 80us/sample - loss: 0.0658 - acc: 0.9781
Epoch 47/100
2782/2782 [==============================] - 0s 87us/sample - loss: 0.0652 - acc: 0.9795
Epoch 48/100
2782/2782 [==============================] - 0s 82us/sample - loss: 0.0647 - acc: 0.9781
Epoch 49/100
2782/2782 [==============================] - 0s 84us/sample - loss: 0.0655 - acc: 0.9774
Epoch 50/100
2782/2782 [==============================] - 0s 85us/sample - loss: 0.0631 - acc: 0.9788
Epoch 51/100
2782/2782 [==============================] - 0s 82us/sample - loss: 0.0625 - acc: 0.9806
Epoch 52/100
2782/2782 [==============================] - 0s 80us/sample - loss: 0.0627 - acc: 0.9792
Epoch 53/100
2782/2782 [==============================] - 0s 80us/sample - loss: 0.0656 - acc: 0.9792
Epoch 54/100
2782/2782 [==============================] - 0s 80us/sample - loss: 0.0603 - acc: 0.9802
Epoch 55/100
2782/2782 [==============================] - 0s 82us/sample - loss: 0.0601 - acc: 0.9781
Epoch 56/100
2782/2782 [==============================] - 0s 84us/sample - loss: 0.0595 - acc: 0.9809
Epoch 57/100
2782/2782 [==============================] - 0s 81us/sample - loss: 0.0592 - acc: 0.9799
Epoch 58/100
2782/2782 [==============================] - 0s 86us/sample - loss: 0.0577 - acc: 0.9817
Epoch 59/100
2782/2782 [==============================] - 0s 83us/sample - loss: 0.0594 - acc: 0.9817
Epoch 60/100
2782/2782 [==============================] - 0s 81us/sample - loss: 0.0553 - acc: 0.9831
Epoch 61/100
2782/2782 [==============================] - 0s 80us/sample - loss: 0.0577 - acc: 0.9813
Epoch 62/100
2782/2782 [==============================] - 0s 80us/sample - loss: 0.0559 - acc: 0.9824
Epoch 63/100
2782/2782 [==============================] - 0s 80us/sample - loss: 0.0556 - acc: 0.9795
Epoch 64/100
2782/2782 [==============================] - 0s 83us/sample - loss: 0.0566 - acc: 0.9827
Epoch 65/100
2782/2782 [==============================] - 0s 79us/sample - loss: 0.0548 - acc: 0.9835
Epoch 66/100
2782/2782 [==============================] - 0s 75us/sample - loss: 0.0530 - acc: 0.9820
Epoch 67/100
2782/2782 [==============================] - 0s 75us/sample - loss: 0.0563 - acc: 0.9795
Epoch 68/100
2782/2782 [==============================] - 0s 76us/sample - loss: 0.0558 - acc: 0.9817
Epoch 69/100
2782/2782 [==============================] - 0s 87us/sample - loss: 0.0522 - acc: 0.9813
Epoch 70/100
2782/2782 [==============================] - 0s 80us/sample - loss: 0.0530 - acc: 0.9831
Epoch 71/100
2782/2782 [==============================] - 0s 81us/sample - loss: 0.0529 - acc: 0.9806
Epoch 72/100
2782/2782 [==============================] - 0s 83us/sample - loss: 0.0511 - acc: 0.9845
Epoch 73/100
2782/2782 [==============================] - 0s 84us/sample - loss: 0.0509 - acc: 0.9831
Epoch 74/100
2782/2782 [==============================] - 0s 81us/sample - loss: 0.0520 - acc: 0.9820
Epoch 75/100
2782/2782 [==============================] - 0s 94us/sample - loss: 0.0510 - acc: 0.9831
Epoch 76/100
2782/2782 [==============================] - 0s 92us/sample - loss: 0.0492 - acc: 0.9856
Epoch 77/100
2782/2782 [==============================] - 0s 89us/sample - loss: 0.0499 - acc: 0.9845
Epoch 78/100
2782/2782 [==============================] - 0s 77us/sample - loss: 0.0498 - acc: 0.9835
Epoch 79/100
2782/2782 [==============================] - 0s 75us/sample - loss: 0.0510 - acc: 0.9842
Epoch 80/100
2782/2782 [==============================] - 0s 80us/sample - loss: 0.0510 - acc: 0.9820
Epoch 81/100
2782/2782 [==============================] - 0s 75us/sample - loss: 0.0497 - acc: 0.9860
Epoch 82/100
2782/2782 [==============================] - 0s 78us/sample - loss: 0.0472 - acc: 0.9845
Epoch 83/100
2782/2782 [==============================] - 0s 82us/sample - loss: 0.0484 - acc: 0.9849
Epoch 84/100
2782/2782 [==============================] - 0s 76us/sample - loss: 0.0491 - acc: 0.9853
Epoch 85/100
2782/2782 [==============================] - 0s 89us/sample - loss: 0.0473 - acc: 0.9863
Epoch 86/100
2782/2782 [==============================] - 0s 82us/sample - loss: 0.0482 - acc: 0.9842
Epoch 87/100
2782/2782 [==============================] - 0s 81us/sample - loss: 0.0481 - acc: 0.9838
Epoch 88/100
2782/2782 [==============================] - 0s 84us/sample - loss: 0.0512 - acc: 0.9842
Epoch 89/100
2782/2782 [==============================] - 0s 82us/sample - loss: 0.0475 - acc: 0.9863
Epoch 90/100
2782/2782 [==============================] - 0s 80us/sample - loss: 0.0495 - acc: 0.9838
Epoch 91/100
2782/2782 [==============================] - 0s 84us/sample - loss: 0.0490 - acc: 0.9838
Epoch 92/100
2782/2782 [==============================] - 0s 83us/sample - loss: 0.0499 - acc: 0.9838
Epoch 93/100
2782/2782 [==============================] - 0s 82us/sample - loss: 0.0465 - acc: 0.9835
Epoch 94/100
2782/2782 [==============================] - 0s 80us/sample - loss: 0.0503 - acc: 0.9827
Epoch 95/100
2782/2782 [==============================] - 0s 79us/sample - loss: 0.0451 - acc: 0.9871
Epoch 96/100
2782/2782 [==============================] - 0s 84us/sample - loss: 0.0469 - acc: 0.9835
Epoch 97/100
2782/2782 [==============================] - 0s 82us/sample - loss: 0.0466 - acc: 0.9842
Epoch 98/100
2782/2782 [==============================] - 0s 81us/sample - loss: 0.0494 - acc: 0.9849
Epoch 99/100
2782/2782 [==============================] - 0s 82us/sample - loss: 0.0454 - acc: 0.9860
Epoch 100/100
2782/2782 [==============================] - 0s 78us/sample - loss: 0.0479 - acc: 0.9849

In [223]:
# get the validation data
score = model.evaluate(features_test, labels_num_test, verbose=1)

1194/1194 [==============================] - 0s 31us/sample - loss: 0.4699 - acc: 0.8300

In [226]:
print("loss score: ",  score[0])

loss score:  0.46993591165453996

In [225]:
print("test accuracy: ", score[1])

test accuracy:  0.82998323